name: Manual Workflow with Branch Input

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'  # Default branch if none is specified

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branchName }}

    - name: Run a one-line script
      run: echo Hello, world from ${{ github.event.inputs.branchName }}!

    - name: Run a multi-line script
      run: |
        echo Add other commands you want to run here
        echo this feature
