name: Hello World Workflow

on:
  push:
    branches:
      - feature # Replace this with the name of your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, GitHub Actions!"
